### ISSUE TITLE
Atualização do ``xmltodict`` quebrou a aplicação

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/porteira#20]
http://pypi.python.org/pypi/xmltodict/0.4.1 -> atualizado em 20/12/2012

``` python
Traceback (most recent call last):
632  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/mocker.py", line 149, in test_method_wrapper
633    result = test_method()
634  File "/home/travis/builds/scieloorg/SciELO-Manager/scielomanager/utils/tests/tests_articlexmldataextractor.py", line 137, in test_get_front_meta
635    self.assertEqual(extr.get_front_meta(), json.load(expected_result))
636  File "/home/travis/builds/scieloorg/SciELO-Manager/scielomanager/../scielomanager/utils/extractors.py", line 197, in get_front_meta
637    data.update(self._extract_front_article_meta())
638  File "/home/travis/builds/scieloorg/SciELO-Manager/scielomanager/../scielomanager/utils/extractors.py", line 166, in _extract_front_article_meta
639    abs_text = self._schema.serialize(abs_as_dict).replace('<?xml version="1.0" encoding="utf-8"?>\n', '')
640  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/porteira/porteira.py", line 85, in serialize
641    return xmltodict.unparse(dict_input, **kwargs)
642  File "/home/travis/virtualenv/python2.7/local/lib/python2.7/site-packages/xmltodict.py", line 231, in unparse
643    ((key, value),) = item.items()
644ValueError: too many values to unpack
```

**Comment by jamilatta** [comment]
Na verdade a assinatura do método serialize não eperava parâmetros não nomeados. Realizado ajuste, disponível no PyPi.

Execute: pip install porteira --upgrade
